### ISSUE TITLE
Generated SMT2 could be optimized/simplified

### ISSUE THREAD

**Issue by philippemerle** [CVC4/org.alloytools.alloy#11]
**Is your feature request related to a problem? Please describe.**

The SMT2 code generated by the CVC4 Relational Solver could be optimized/simplified.

**Describe the solution you'd like**

1) Disjoint signatures assertions are generated two times, i.e.
   `(assert (= (intersection |this/XXX | |this/YYY |) atomNone))`

2) each field multiplicity assertion contains redundant expressions, i.e.
`       (and
          (and true
            (member |this | |this/XXX |))
          (and true true))
`
could be simplified to
`        (member |this | |this/XXX |)`
The `and` formulas and `true` constants are useless.

3) generated `(assert true)`assertions are useless and could be removed.

4) Following two assertions are generated for each Alloy command.
`; integer/univInt = Int
  (assert
    (= |integer/univInt | univInt))
  ; (all x,y | x = y <=> x -> y in (integer/univInt <: idenInt))
  (assert ... )
`
These two assertions could be generated only one time before generating commands.

**Describe alternatives you've considered**

**Additional context**

Issue copied from https://github.com/philippemerle/Alloy2CVC4/issues/3

**Comment by mudathirmahgoub** [comment]
Thanks for the optimization suggestions. They are now implemented and merged into master. These changes are simple steps towards major optimization.
