### ISSUE TITLE
Incorrect results

### ISSUE THREAD

**Issue by philippemerle** [CVC4/org.alloytools.alloy#12]
**Describe the bug**

Given the following Alloy specification

  sig A {}
  sig LoneA { a : lone A }
  sig OneA  { a : one A  }
  // this assertion is true due to the field 'a' declaration.
  check no_LoneA_with_several_A { no x : LoneA | #(x.a) > 1 } expect 0
  // this assertion is true due to the field 'a' declaration.
  check no_OneA_without_A { no x : OneA | no x.a } expect 0
  // this assertion is true due to the field 'a' declaration.
  check no_OneA_with_several_A { no x : OneA | #(x.a) > 1 } expect 0

the three assertions are trivially true.
With the CVC4 Relational Solver for Alloy, these three assertions are false!!!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Copied from https://github.com/philippemerle/Alloy2CVC4/issues/2

**Comment by mudathirmahgoub** [comment]
Fixed and pushed to master.
